/** @format */

import {
  MdFitnessCenter,
  MdHealthAndSafety,
  MdSelfImprovement,
  MdLaptop,
  MdWorkspacePremium,
  MdDesignServices,
  MdHome,
  MdSick,
  MdWork,
  MdFlight,
  MdTrendingUp,
} from "react-icons/md";
import type { BenefitCardProps } from "./BenefitCard";

export const BENEFITS: BenefitCardProps[] = [
  {
    category: "WELLNESS",
    name: "Pinefit Subsidy",
    description: "Gym membership and fitness program allowance",
    subsidyPercentage: "50%",
    vendorDetails: "PineFit Gym Network",
    eligibilityCriteria: "After 90 days of employment",
    contractLink: "/contracts/pinefit",
    status: "ACTIVE",
    eligibilityRules: [
      {
        rule: "Tenure ≥ 90 days",
        passed: true,
        detail: "185 days — meets requirement",
      },
      {
        rule: "Employment status active",
        passed: true,
        detail: "Full-time employee",
      },
    ],
    icon: <MdFitnessCenter size={24} />,
    iconBgColor: "bg-[#E91E63]/20",
    iconColor: "text-[#E91E63]",
  },
  {
    category: "HEALTH",
    name: "Private Insurance",
    description: "Additional private health insurance coverage",
    subsidyPercentage: "50%",
    vendorDetails: "Blue Cross Health Partners",
    eligibilityCriteria: "After 6 months of employment",
    contractLink: "/contracts/private-insurance",
    status: "ACTIVE",
    eligibilityRules: [
      {
        rule: "Tenure ≥ 6 months",
        passed: true,
        detail: "185 days — meets requirement",
      },
      {
        rule: "Primary insurance enrolled",
        passed: true,
        detail: "Core plan active",
      },
    ],
    icon: <MdHealthAndSafety size={24} />,
    iconBgColor: "bg-[#2196F3]/20",
    iconColor: "text-[#2196F3]",
  },
  {
    category: "WELLNESS",
    name: "Digital Wellness",
    description: "Core digital wellness and mental health resources",
    subsidyPercentage: "100%",
    vendorDetails: "Headspace, Calm (Core tier)",
    eligibilityCriteria: "Available from day 1",
    contractLink: "/contracts/digital-wellness",
    status: "ACTIVE",
    eligibilityRules: [
      {
        rule: "Available from day 1",
        passed: true,
        detail: "Core benefit — no tenure required",
      },
    ],
    icon: <MdSelfImprovement size={24} />,
    iconBgColor: "bg-[#9C27B0]/20",
    iconColor: "text-[#9C27B0]",
  },
  {
    category: "EQUIPMENT",
    name: "MacBook Subsidy",
    description: "Work laptop purchase or upgrade allowance",
    subsidyPercentage: "50%",
    vendorDetails: "Apple Authorized Reseller",
    eligibilityCriteria: "After 1 year of employment",
    contractLink: "/contracts/macbook",
    status: "ELIGIBLE",
    eligibilityRules: [
      {
        rule: "Tenure ≥ 1 year",
        passed: true,
        detail: "365 days — meets requirement",
      },
      {
        rule: "No recent equipment grant",
        passed: true,
        detail: "Last grant: N/A",
      },
    ],
    icon: <MdLaptop size={24} />,
    iconBgColor: "bg-[#607D8B]/20",
    iconColor: "text-[#607D8B]",
  },
  {
    category: "CAREER",
    name: "Extra Responsibility",
    description: "Recognition and compensation for additional responsibilities",
    vendorDetails: "Internal",
    eligibilityCriteria: "Manager approval for project-based or role expansion",
    contractLink: "/contracts/extra-responsibility",
    status: "PENDING",
    eligibilityRules: [
      { rule: "Manager approval", passed: true, detail: "Request submitted" },
      {
        rule: "Request under review",
        passed: false,
        detail: "Awaiting HR approval",
      },
    ],
    icon: <MdWorkspacePremium size={24} />,
    iconBgColor: "bg-[#FF9800]/20",
    iconColor: "text-[#FF9800]",
  },
  {
    category: "TOOLS",
    name: "UX Engineering Tool",
    description: "Design and prototyping software subscription",
    subsidyPercentage: "100%",
    vendorDetails: "Figma, Adobe XD",
    eligibilityCriteria: "UX/Design role or manager approval",
    contractLink: "/contracts/ux-tools",
    status: "ELIGIBLE",
    eligibilityRules: [
      {
        rule: "UX/Design role or approval",
        passed: true,
        detail: "Role qualifies",
      },
      {
        rule: "No active subscription",
        passed: true,
        detail: "Eligible to request",
      },
    ],
    icon: <MdDesignServices size={24} />,
    iconBgColor: "bg-[#00BCD4]/20",
    iconColor: "text-[#00BCD4]",
  },
  {
    category: "FINANCIAL",
    name: "Down Payment Assistance",
    description: "Housing down payment support program",
    vendorDetails: "Partner mortgage lenders",
    eligibilityCriteria: "After 2 years of employment",
    contractLink: "/contracts/down-payment",
    status: "LOCKED",
    lockReason: "Requires 2 years tenure — 185 days (6 months) currently",
    eligibilityRules: [
      {
        rule: "Tenure ≥ 2 years",
        passed: false,
        detail: "185 days (6 months) — need 730 days",
      },
      {
        rule: "Employment status active",
        passed: true,
        detail: "Full-time employee",
      },
    ],
    icon: <MdHome size={24} />,
    iconBgColor: "bg-[#4CAF50]/20",
    iconColor: "text-[#4CAF50]",
  },
  {
    category: "TIME OFF",
    name: "Shit Happened Days",
    description: "Personal days for unexpected life events",
    vendorDetails: "Internal policy",
    eligibilityCriteria: "Available from day 1, 3 days per year",
    contractLink: "/contracts/shit-happened-days",
    status: "ACTIVE",
    eligibilityRules: [
      { rule: "Available from day 1", passed: true, detail: "3 days per year" },
      {
        rule: "Days remaining this year",
        passed: true,
        detail: "3 of 3 available",
      },
    ],
    icon: <MdSick size={24} />,
    iconBgColor: "bg-[#F44336]/20",
    iconColor: "text-[#F44336]",
  },
  {
    category: "WORKPLACE",
    name: "Remote Work",
    description: "Flexible remote work arrangement",
    vendorDetails: "Internal policy",
    eligibilityCriteria: "Role and manager approval for hybrid or full remote",
    contractLink: "/contracts/remote-work",
    status: "ELIGIBLE",
    eligibilityRules: [
      { rule: "Role allows remote", passed: true, detail: "Engineering role" },
      { rule: "Manager approval", passed: true, detail: "Approved for hybrid" },
    ],
    icon: <MdWork size={24} />,
    iconBgColor: "bg-[#673AB7]/20",
    iconColor: "text-[#673AB7]",
  },
  {
    category: "FINANCIAL",
    name: "Travel Subsidy",
    description: "Business and commute travel allowance",
    subsidyPercentage: "50%",
    vendorDetails: "Approved travel providers",
    eligibilityCriteria: "Travel-related roles or business need",
    contractLink: "/contracts/travel",
    status: "PENDING",
    eligibilityRules: [
      {
        rule: "Travel-related role or need",
        passed: true,
        detail: "Business travel required",
      },
      {
        rule: "Request under review",
        passed: false,
        detail: "Awaiting finance approval",
      },
    ],
    icon: <MdFlight size={24} />,
    iconBgColor: "bg-[#03A9F4]/20",
    iconColor: "text-[#03A9F4]",
  },
  {
    category: "PERFORMANCE",
    name: "Bonus Based on OKR",
    description: "Performance-based bonus tied to OKR achievement",
    vendorDetails: "Internal",
    eligibilityCriteria: "OKR performance ≥ 80%",
    contractLink: "/contracts/okr-bonus",
    status: "LOCKED",
    lockReason: "OKR not submitted for Q1 2025",
    eligibilityRules: [
      {
        rule: "OKR submitted for current quarter",
        passed: false,
        detail: "OKR not submitted for Q1 2025",
      },
      {
        rule: "OKR performance ≥ 80%",
        passed: true,
        detail: "82% — meets threshold",
      },
    ],
    icon: <MdTrendingUp size={24} />,
    iconBgColor: "bg-[#8BC34A]/20",
    iconColor: "text-[#8BC34A]",
  },
];
