/** Дүрмийн operator-ууд (харьцуулалт) */
export const OPERATORS = [
  { value: 'eq', label: 'Тэнцүү (eq)' },
  { value: 'lt', label: 'Бага (lt)' },
  { value: 'lte', label: 'Бага буюу тэнцүү (lte)' },
  { value: 'gte', label: 'Их буюу тэнцүү (gte)' },
  { value: 'gt', label: 'Их (gt)' },
] as const;

/** Алдааны мессежүүд (нэг дор, тодорхой) */
export const ERROR_MESSAGES = {
  NAME_REQUIRED: 'Нэр заавал бөглөнө үү.',
  CATEGORY_REQUIRED: 'Ангилал заавал бөглөнө үү.',
  SUBSIDY_RANGE: 'Хөнгөлөлтийн хувь 0–100 хооронд байх ёстой.',
  SELECT_BENEFIT: 'Дүрэм тохируулах benefit-ийг сонгоно уу.',
  RULE_VALUE_REQUIRED: 'Дүрмийн утга бөглөнө үү.',
  D1_CREATE: 'D1 руу benefit нэмэхэд алдаа гарлаа: ',
  CONFIG_LOAD: 'Дүрмийн config унших үед алдаа: ',
  CONFIG_SAVE: 'Дүрэм хадгалах үед алдаа: ',
  BENEFITS_LOAD: 'D1-ээс benefit жагсаалт татах үед алдаа: ',
  FINANCE_CHECK_REQUIRED: 'Finance check заавал хийнэ үү.',
  CONTRACT_NUMBER_REQUIRED: 'Гэрээний дугаар заавал бөглөнө үү.',
  CONTRACT_NAME_REQUIRED: 'Гэрээний нэр заавал бөглөнө үү.',
  CONTRACT_FILE_REQUIRED: 'Гэрээний файл upload хийнэ үү.',
} as const;

import type { AddBenefitFormState } from './types';

export const DEFAULT_FORM: AddBenefitFormState = {
  name: '',
  description: '',
  category: 'wellness',
  subsidyPercent: 0,
  financeCheck: false,
  requiresContract: false,
  contractNumber: '',
  contractName: '',
  contractFileName: '',
  contractUrl: '',
};

/** Benefit санал болгох жишээнүүд — Suggest товч дархад field-үүдийг автоматаар бөглөнө */
export const BENEFIT_SUGGESTIONS: AddBenefitFormState[] = [
  {
    name: 'Gym Pinefit',
    description: 'Gym membership reimbursement for employee wellness.',
    category: 'Wellness',
    subsidyPercent: 80,
    financeCheck: false,
    requiresContract: true,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
  {
    name: 'Health Insurance',
    description: 'Company-supported health insurance package.',
    category: 'Health',
    subsidyPercent: 100,
    financeCheck: false,
    requiresContract: true,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
  {
    name: 'Laptop Allowance',
    description: 'Allowance for purchasing or upgrading work laptop.',
    category: 'Equipment',
    subsidyPercent: 50,
    financeCheck: false,
    requiresContract: false,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
  {
    name: 'Learning Budget',
    description: 'Annual budget for courses, certifications, and learning.',
    category: 'Career Development',
    subsidyPercent: 60,
    financeCheck: false,
    requiresContract: false,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
  {
    name: 'Flexible Hours',
    description: 'Flexible working schedule option based on team policy.',
    category: 'Flexibility',
    subsidyPercent: 0,
    financeCheck: false,
    requiresContract: false,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
  {
    name: 'Mental Health Support',
    description: 'Counseling and mental health support benefit.',
    category: 'Wellness',
    subsidyPercent: 100,
    financeCheck: false,
    requiresContract: false,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
  {
    name: 'Home Office Stipend',
    description: 'Stipend for home office setup and equipment.',
    category: 'Equipment',
    subsidyPercent: 30,
    financeCheck: false,
    requiresContract: false,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
  {
    name: 'Transport Allowance',
    description: 'Monthly transport reimbursement support.',
    category: 'Financial',
    subsidyPercent: 40,
    financeCheck: false,
    requiresContract: false,
    contractNumber: '',
    contractName: '',
    contractFileName: '',
    contractUrl: '',
  },
];
